name: CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
        
    - name: Install dependencies
      run: npm install
      
    - name: Run ESLint
      run: npm run lint
      
    - name: Run Karma Tests
      run: npm run ng -- test --watch=false --browsers=ChromeHeadless\

    - name: Set up SonarQube
      uses: sonarsource/sonarqube-action@v1
      with:
        sonar-login: ${{ secrets.SONAR_TOKEN }}
        sonar-host: ${{ secrets.SONAR_HOST_URL }}
        sonar-project-key: hello-world
        sonar-project-name: hello-world
        sonar-project-version: 1.0