name: CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
        
    - name: Install dependencies
      run: npm install
      
    - name: Run ESLint
      run: npm run lin
      
    - name: Run Karma Tests
      run: npm run ng -- test --watch=false --browsers=ChromeHeadless\

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    - uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  rollback:
    runs-on: ubuntu-latest
    needs: build
    if: failure()

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with: 
        ref: 732526b992b19ffd97307e65316113971ff639d6
      env:
        ACTIONS_CACHE_NAME: no-cache
    - name: Rollback to Previous Commit
      run: |
        # Rollback to the previous commit
        git fetch
        git reset --hard 732526b992b19ffd97307e65316113971ff639d6
    - name: Push Rollback to Repository
      run: |
        # Push the rollback commit to the repository
        git pull
        git push origin HEAD:master